In [102]:
import os
import pandas as pd
import numpy as np

In [103]:
folder_name=[]
for i in os.listdir(r"D:\Data Science\Dataset\bbc"):
    if ".TXT" not in i:
        folder_name.append(i)
folder_name    

['business', 'entertainment', 'politics', 'sport', 'tech']

In [104]:
dataset=[]
new_dataset=[]
import glob
for i in folder_name:
    for j in glob.glob("D:\\Data Science\\Dataset\\bbc\\"+i+"\\*.txt"):
        f=open(j)
        dataset.append([i,j.split("\\")[-1],f.read()])
        new_dataset.append([f.read()]) 

In [105]:
dataset=pd.DataFrame(np.array(dataset))

In [106]:
dataset.head()

0        1                                                  2
0  business  001.txt  Ad sales boost Time Warner profit\n\nQuarterly...
1  business  002.txt  Dollar gains on Greenspan speech\n\nThe dollar...
2  business  003.txt  Yukos unit buyer faces loan claim\n\nThe owner...
3  business  004.txt  High fuel prices hit BA's profits\n\nBritish A...
4  business  005.txt  Pernod takeover talk lifts Domecq\n\nShares in...

In [92]:
dataset[0].value_counts()

sport            511
business         510
politics         416
tech             401
entertainment    386
Name: 0, dtype: int64

In [107]:
y=dataset[0]
x=dataset[2]

In [108]:
dummy_table=pd.get_dummies(y)

In [111]:
dataset.columns=['y','file name','x']

In [116]:
for i in dummy_table:
    dataset[i]=dummy_table[i]

In [117]:
dataset.head()

y file name                                                  x  \
0  business   001.txt  Ad sales boost Time Warner profit\n\nQuarterly...   
1  business   002.txt  Dollar gains on Greenspan speech\n\nThe dollar...   
2  business   003.txt  Yukos unit buyer faces loan claim\n\nThe owner...   
3  business   004.txt  High fuel prices hit BA's profits\n\nBritish A...   
4  business   005.txt  Pernod takeover talk lifts Domecq\n\nShares in...   

   business  entertainment  politics  sport  tech  
0         1              0         0      0     0  
1         1              0         0      0     0  
2         1              0         0      0     0  
3         1              0         0      0     0  
4         1              0         0      0     0

In [114]:
from sklearn.linear_model import LogisticRegression

In [98]:
predicted_proba=[]
for i in dataset['y'].unique():
    d1=dataset[dataset[i]==1]
    d2=dataset[dataset[i]!=1].sample(d1.shape[0])
    final_dataset=d1.append(d2)
    x=final_dataset['x']
    y=final_dataset[i]
    from sklearn.metrics import confusion_matrix,accuracy_score
    from sklearn.feature_extraction.text import TfidfVectorizer
    vectorizer = TfidfVectorizer()
    vectorizer.fit(x)
    transformed_x=vectorizer.transform(x)
    print(i,x.shape,y.shape)
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(transformed_x, y, test_size=0.2)
    print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)
    lr=LogisticRegression()
    lr.fit(X_train,y_train)
    print("predicting for category",i)
    print(confusion_matrix(y_test,lr.predict(X_test)))
    print(accuracy_score(y_test,lr.predict(X_test)))
    predicted_proba.append(lr.predict_proba(X_test))
    
    print("*****************************************")
    
    print("                        ")

business (1020,) (1020,)
(816, 20417) (204, 20417) (816,) (204,)
predicting for category business
[[ 89   0]
 [  3 112]]
0.9852941176470589
*****************************************
                        
entertainment (772,) (772,)
(617, 18908) (155, 18908) (617,) (155,)
predicting for category entertainment
[[82  1]
 [ 4 68]]
0.967741935483871
*****************************************
                        
politics (832,) (832,)
(665, 18814) (167, 18814) (665,) (167,)
predicting for category politics
[[77  1]
 [ 6 83]]
0.9580838323353293
*****************************************
                        
sport (1022,) (1022,)
(817, 20420) (205, 20420) (817,) (205,)
predicting for category sport
[[106   1]
 [  1  97]]
0.9902439024390244
*****************************************
                        
tech (802,) (802,)
(641, 18898) (161, 18898) (641,) (161,)
predicting for category tech
[[83  3]
 [ 3 72]]
0.9627329192546584
*****************************************
             

In [99]:
predicted_proba=np.array(predicted_proba)

In [100]:
predicted_proba.shape

(5,)

In [17]:
predicted_proba[0].shape

(204, 2)

In [18]:
predicted_proba[1].shape,predicted_proba[2].shape,predicted_proba[3].shape

((155, 2), (167, 2), (205, 2))

In [19]:
predicted_proba[0][:,1][0:5]


array([0.21096824, 0.23623976, 0.39336271, 0.78160539, 0.85388924])

In [20]:
predicted_proba[1][:,1][0:5]

array([0.37056611, 0.87230734, 0.31179204, 0.19580788, 0.38650027])

In [21]:
predicted_proba[2][:,1][0:5]


array([0.19344062, 0.61618496, 0.79399777, 0.24105182, 0.48865367])

In [22]:
dataset

y fille name                                                  x  \
0     business    001.txt  Ad sales boost Time Warner profit\n\nQuarterly...   
1     business    002.txt  Dollar gains on Greenspan speech\n\nThe dollar...   
2     business    003.txt  Yukos unit buyer faces loan claim\n\nThe owner...   
3     business    004.txt  High fuel prices hit BA's profits\n\nBritish A...   
4     business    005.txt  Pernod takeover talk lifts Domecq\n\nShares in...   
...        ...        ...                                                ...   
2219      tech    397.txt  BT program to beat dialler scams\n\nBT is intr...   
2220      tech    398.txt  Spam e-mails tempt net shoppers\n\nComputer us...   
2221      tech    399.txt  Be careful how you code\n\nA new European dire...   
2222      tech    400.txt  US cyber security chief resigns\n\nThe man mak...   
2223      tech    401.txt  Losing yourself in online gaming\n\nOnline rol...   

      business  entertainment  politics  sport  tech  
0            1              0         0      0     0  
1            1              0         0      0     0  
2            1              0         0      0     0  
3            1              0         0      0     0  
4            1              0         0      0     0  
...        ...            ...       ...    ...   ...  
2219         0              0         0      0     1  
2220         0              0         0      0     1  
2221         0              0         0      0     1  
2222         0              0         0      0     1  
2223         0              0         0      0     1  

[2224 rows x 8 columns]