#### NLP, GENISM, NLTK, SPACY, 
#### AI, TENSORFLOW AND KERAS FOR CODING
#### Understanding the data and representation in a number form

### Text Data has to be converted different data format

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.DataFrame(['I bought a laptop and its too good','but the batter gets drained very fast'])

In [4]:
df.head()

0
0     I bought a laptop and its too good
1  but the batter gets drained very fast

In [5]:
import nltk
import warnings
nltk.download('punkt')
#Natural Language tool kit

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Anil\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [6]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [10]:
text='I bought a laptop and its too good but the batter gets drained very fast'

In [11]:
print(word_tokenize(text))

['I', 'bought', 'a', 'laptop', 'and', 'its', 'too', 'good', 'but', 'the', 'batter', 'gets', 'drained', 'very', 'fast']


In [12]:
print(sent_tokenize(text))

['I bought a laptop and its too good but the batter gets drained very fast']


In [13]:
####Stop Words

In [14]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Anil\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [15]:
stop_words=set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [16]:
list(stop_words)[0:10]

['my',
 'about',
 'wouldn',
 'aren',
 'had',
 "that'll",
 'all',
 'itself',
 'are',
 'mightn']

### Preprocessing of Text Data
### Lemmitization & Stemming

### Stemming : Removing the Ending parts of the words

In [17]:
don='Programmer,Programs,Programee'

In [18]:
import nltk
nltk.download('wordnet')
from nltk.stem import PorterStemmer
ps=PorterStemmer()
word=word_tokenize(don)


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Anil\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [19]:
for i in word:
     print(i, ps.stem(i))

Programmer programm
, ,
Programs program
, ,
Programee programe


### Lemitization : A Tree of how words are linked with each others and for every word it maps with the root nodes

In [20]:
import nltk
nltk.download('wordnet')

words=['rocks','corpora','better']

from nltk.stem import WordNetLemmatizer
wlm=WordNetLemmatizer()

for i in words:
    print(i,wlm.lemmatize(i,pos ='a'))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Anil\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


rocks rocks
corpora corpora
better good


In [21]:
text='I bought a laptop and its dam good,but the batter is shit'

In [22]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Anil\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [23]:
word=word_tokenize(text)
for i in word:
    print(i,nltk.pos_tag(str(i)))

I [('I', 'PRP')]
bought [('b', 'NN'), ('o', 'NN'), ('u', 'JJ'), ('g', 'NN'), ('h', 'NN'), ('t', 'NN')]
a [('a', 'DT')]
laptop [('l', 'NN'), ('a', 'DT'), ('p', 'NN'), ('t', 'NN'), ('o', 'NN'), ('p', 'NN')]
and [('a', 'DT'), ('n', 'JJ'), ('d', 'NN')]
its [('i', 'NN'), ('t', 'VBP'), ('s', 'NN')]
dam [('d', 'VB'), ('a', 'DT'), ('m', 'NN')]
good [('g', 'NN'), ('o', 'MD'), ('o', 'VB'), ('d', 'NN')]
, [(',', ',')]
but [('b', 'NN'), ('u', 'NN'), ('t', 'NN')]
the [('t', 'NN'), ('h', 'NN'), ('e', 'NN')]
batter [('b', 'VB'), ('a', 'DT'), ('t', 'NN'), ('t', 'NN'), ('e', 'NN'), ('r', 'NN')]
is [('i', 'NN'), ('s', 'VBP')]
shit [('s', 'NN'), ('h', 'NN'), ('i', 'NN'), ('t', 'VBP')]


In [24]:
word=word_tokenize(text)
nltk.pos_tag(word)

[('I', 'PRP'),
 ('bought', 'VBD'),
 ('a', 'DT'),
 ('laptop', 'JJ'),
 ('and', 'CC'),
 ('its', 'PRP$'),
 ('dam', 'NN'),
 ('good', 'JJ'),
 (',', ','),
 ('but', 'CC'),
 ('the', 'DT'),
 ('batter', 'NN'),
 ('is', 'VBZ'),
 ('shit', 'JJ')]

### Preprocessing steps
### If the data is given to us in text form, cannot be directly used in analystical algorithm
### These data has to converted to numerical form

In [25]:
df

0
0     I bought a laptop and its too good
1  but the batter gets drained very fast

In [26]:
from nltk.tokenize import word_tokenize,sent_tokenize
print(word_tokenize(df[0][0]))
print(word_tokenize(df[0][1]))

['I', 'bought', 'a', 'laptop', 'and', 'its', 'too', 'good']
['but', 'the', 'batter', 'gets', 'drained', 'very', 'fast']


In [27]:
list1=word_tokenize(df[0][0])
list2=word_tokenize(df[0][0])

In [28]:
pd.DataFrame(columns=list1)

Empty DataFrame
Columns: [I, bought, a, laptop, and, its, too, good]
Index: []

#### NLP, GENISM, NLTK, SPACY 


## Sentiment Analysis

### Precprocessing steps for NLP
#### Remove all stopwords,Duplicates.
#### Stemming & Lemma,
#### NER (Named Entity Recognization)
#### POS Tagging
#### DTM (Document Term Matrix)
### Model Building
### Validation 
### Deployment

#### Sentiment Analysis Classifier

In [29]:
import numpy as np
import pandas as pd

In [30]:
df=pd.read_csv(r'D:\Data Science\Dataset\Amazon_Unlocked_Mobile\Amazon_Unlocked_Mobile.csv')

In [31]:
df.head()

Product Name Brand Name   Price  \
0  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
1  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
2  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
3  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
4  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   

   Rating                                            Reviews  Review Votes  
0       5  I feel so LUCKY to have found this used (phone...           1.0  
1       4  nice phone, nice up grade from my pantach revu...           0.0  
2       5                                       Very pleased           0.0  
3       4  It works good but it goes slow sometimes but i...           0.0  
4       4  Great phone to replace my lost phone. The only...           0.0

In [32]:
x=df['Reviews']
y=df['Rating']

In [79]:
np.unique(y.values)

array([1, 2, 3, 4, 5], dtype=int64)

In [80]:
sentiment=[]
for i in y.values:
    if i<3:
        sentiment.append('negative')
    elif i==3:
        sentiment.append('Neutral')
    else:
        sentiment.append('positive')
        

In [81]:
df['sentiment']=sentiment

In [82]:
df.head()

Product Name Brand Name   Price  \
0  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
1  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
2  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
3  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
4  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   

   Rating                                            Reviews  Review Votes  \
0       5  I feel so LUCKY to have found this used (phone...           1.0   
1       4  nice phone, nice up grade from my pantach revu...           0.0   
2       5                                       Very pleased           0.0   
3       4  It works good but it goes slow sometimes but i...           0.0   
4       4  Great phone to replace my lost phone. The only...           0.0   

  sentiment  
0  positive  
1  positive  
2  positive  
3  positive  
4  positive

In [95]:
df['sentiment'].value_counts()

positive    284997
negative     97078
Neutral      31765
Name: sentiment, dtype: int64

In [96]:
d1=df[df['sentiment']=='Neutral']
d2=df[df['sentiment']=='negative'].sample(31765)
d3=df[df['sentiment']=='positive'].sample(31765)

In [98]:
m1=d1.append(d2)
final_dataset=m1.append(d3)

In [99]:
final_dataset['sentiment'].value_counts()

Neutral     31765
positive    31765
negative    31765
Name: sentiment, dtype: int64

In [100]:
y=final_dataset['sentiment']
x=final_dataset['Reviews']

In [104]:
final_dataset.dropna(how='any',axis=0,inplace=True)

In [105]:
x=df['Reviews']
y=df['sentiment']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(331072,) (82768,) (331072,) (82768,)


In [107]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(stop_words='english',ngram_range=(1,2))
tf.fit(X_train)
X_train_transformed=tf.transform(X_train)
X_test_transformed=tf.transform(X_test)

In [109]:
X_train_transformed

<61780x496065 sparse matrix of type '<class 'numpy.float64'>'
	with 2367831 stored elements in Compressed Sparse Row format>

In [110]:
tf.get_feature_names()

['00',
 '000',
 '0000',
 '00000',
 '000000',
 '0000000',
 '0000from',
 '000mah',
 '000mh',
 '002',
 '0044',
 '00emotional',
 '00k',
 '00over',
 '00pm',
 '00so',
 '00time',
 '01',
 '011',
 '012',
 '014',
 '02',
 '02mbps',
 '03',
 '0330',
 '04',
 '0400',
 '049',
 '04th',
 '05',
 '051',
 '05685577',
 '0572013',
 '05mps',
 '06',
 '061',
 '066',
 '07',
 '070',
 '0780',
 '07mpimei',
 '08',
 '0808',
 '0848983',
 '08mms',
 '08this',
 '09',
 '0909853',
 '09on',
 '0_print_120716',
 '0a',
 '0c',
 '0cesqfjad',
 '0fm',
 '0g',
 '0gb',
 '0ghz',
 '0hd',
 '0i',
 '0ii',
 '0k',
 '0l',
 '0lte',
 '0marshmallow',
 '0mp',
 '0mps87ysgrvp9gkhps5d',
 '0nly',
 '0s',
 '0social',
 '0stars',
 '0the',
 '0ui',
 '0x80070002',
 '10',
 '100',
 '1000',
 '10000',
 '100000',
 '1000000',
 '10000m',
 '1000m',
 '1000s',
 '1001',
 '10050',
 '100gb',
 '100hours',
 '100k',
 '100mb',
 '100mph',
 '100s',
 '100usd',
 '100x',
 '101',
 '1012017',
 '102',
 '1020',
 '103',
 '1030',
 '10327',
 '1037',
 '104',
 '1048576k',
 '105',
 '1057

In [111]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words =set(stopwords.words("english"))

print(len(stop_words))

stop_words=list(stop_words)

179


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Anil\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [112]:
stop_words.extend(['a'])

After Preprocessing

In [113]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [118]:
from sklearn.tree import DecisionTreeClassifier

dt=DecisionTreeClassifier()
dt.fit(X_train_transformed,y_train)
dt.predict(X_test_transformed)
print(confusion_matrix(y_test,dt.predict(X_test_transformed)))

[[3922  610  664]
 [ 733 3827  485]
 [ 668  352 4185]]


In [116]:
print(accuracy_score(y_test,dt.predict(X_test_transformed)))

0.7738573093357504
