In [1]:
#### KNN Regression

In [34]:
import pandas as pd
import numpy as np

In [35]:

columns1=['x'+str(i) for i in range(1,21)] ## List Comprehension
columns1[19]='y'

In [36]:
columns1

['x1',
 'x2',
 'x3',
 'x4',
 'x5',
 'x6',
 'x7',
 'x8',
 'x9',
 'x10',
 'x11',
 'x12',
 'x13',
 'x14',
 'x15',
 'x16',
 'x17',
 'x18',
 'x19',
 'y']

In [37]:
df=pd.DataFrame(np.random.randint(0,1000,(100,20)),columns=columns1)

In [38]:
df.shape

(100, 20)

In [39]:
y=df['y']
x=df.drop('y',axis=1)

In [40]:
x

x1   x2   x3   x4   x5   x6   x7   x8   x9  x10  x11  x12  x13  x14  x15  \
0   506  320  291  307  428   49  559  247  993  939  580  424  223  964  917   
1   799  113  862  451  122  520  876  442  340  269  193    5  898  259  356   
2    29  209  910  764  584   61  577  418  418  293   17  881  228  439  968   
3   874  562  992  925  656  531  141  555  154  535   84   63  329  800  853   
4   212  840  540  603  450  795   50   37  123  515  670  376  238  811  823   
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
95  412  851  763  215  713  586  563  977  190  923   40  640    4   50  827   
96  102  990  844  642  150  496  773  419  797  509  822  968  802  768  338   
97  558  108  898  447  404  370  653  876  623  302  331   71   70  652  968   
98  735  843   41  453  938  902  491   46  685  865  724   82  677  354   79   
99  482  974  933  711  926  216  234  494   25  191  903  365  770  728  428   

    x16  x17  x18  x19  
0   855  320  182  585  
1   705  594  875  842  
2   816  719  513  842  
3   620  324  245  993  
4   535  614  879  704  
..  ...  ...  ...  ...  
95  840  773  711  648  
96  831  615  966  303  
97  801  567  665  335  
98  869  995  928  184  
99  602  687  226  564  

[100 rows x 19 columns]

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [42]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(80, 19) (20, 19) (80,) (20,)


In [43]:
distances = []
for i in x_test.values:
    for j in x_train.values:
        distances.append(np.sqrt(((i-j)*(i-j)).sum()))

In [44]:
len(distances)

1600

In [45]:
distances = np.array(distances)
distance_matrix = distances.reshape(80,20).T
distance_matrix.argmin(axis=1)

array([73, 28, 78, 24, 31, 74, 20, 65, 41, 45, 75, 73, 28, 73, 13, 72, 74,
        3, 60, 30], dtype=int64)

In [46]:
predicted_values = []
for i in distance_matrix.argmin(axis=1):
    print(y[i])

834
901
182
332
808
647
868
555
198
718
935
834
901
834
740
748
647
214
580
473


In [47]:
import seaborn as sns
df= sns.load_dataset('titanic')

df=df[df.describe().columns]
df.fillna(20,inplace=True)


df.shape

df.head()

y=df['fare']
x=df.drop('fare',axis=1)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)
print()


(712, 5) (179, 5) (712,) (179,)



In [48]:
from sklearn.neighbors import KNeighborsRegressor
kn=KNeighborsRegressor(n_neighbors=1)
kn.fit(x_train,y_train)
predicted_values=kn.predict(x_test)

In [49]:
predicted_values[0:10],y_test[0:10]

(array([15.7417,  7.75  ,  7.8292, 12.475 , 30.0708, 30.5   ,  7.225 ,
        20.25  ,  8.05  , 55.    ]),
 709    15.2458
 439    10.5000
 840     7.9250
 720    33.0000
 39     11.2417
 290    78.8500
 300     7.7500
 333    18.0000
 208     7.7500
 136    26.2833
 Name: fare, dtype: float64)

In [50]:
MAE=(abs(y_test-predicted_values).sum())/y_test.shape[0]

In [51]:
MAE

19.686963128491623

In [52]:
#### Confusion Matrix

In [53]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [54]:
from sklearn.metrics import confusion_matrix

In [55]:
from sklearn.neighbors import KNeighborsRegressor
kn=KNeighborsRegressor(n_neighbors=1)
kn.fit(x_train,y_train)
predicted_values=kn.predict(x_test)

In [56]:
MAE=(abs(y_test-predicted_values).sum())/y_test.shape[0]

In [57]:
MAE

19.686963128491623

In [58]:
KNeighborsRegressor()

KNeighborsRegressor()

In [59]:
#Parameter needs to test for different values
# Tune for neighbor with different values

In [66]:
from sklearn.neighbors import KNeighborsRegressor
kn=KNeighborsRegressor(n_neighbors=1)
kn.fit(x_train,y_train)
predicted_values=kn.predict(x_test)
MAE=(abs(y_test-predicted_values).sum())/y_test.shape[0]
print(MAE)

19.686963128491623


In [67]:
from sklearn.neighbors import KNeighborsRegressor
kn=KNeighborsRegressor(n_neighbors=4)
kn.fit(x_train,y_train)
predicted_values=kn.predict(x_test)
MAE=(abs(y_test-predicted_values).sum())/y_test.shape[0]
print(MAE)

16.798531564245813


In [62]:
df.head()

survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

In [68]:
y=df['survived']
x=df.drop('survived',axis=1)

In [71]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)
print(y_test.mean())

(712, 5) (179, 5) (712,) (179,)
0.4134078212290503


In [87]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=5)
kn.fit(x_train,y_train)
predicted_values=kn.predict(x_test)

In [90]:
predicted_values

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1], dtype=int64)

In [91]:
y_test.values

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1], dtype=int64)

In [92]:
compare=pd.DataFrame([y_test.values,predicted_values]).T

In [93]:
compare.columns=['original','pred']

In [94]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test.values,predicted_values)


array([[87, 18],
       [40, 34]], dtype=int64)

In [96]:
compare[(compare['original']==1)& (compare['pred']==1)].shape

(34, 2)

In [98]:
compare[(compare['original']==1)& (compare['pred']==0)].shape

(40, 2)

In [99]:
compare[(compare['original']==0)& (compare['pred']==1)].shape

(18, 2)

In [100]:
compare[(compare['original']==0)& (compare['pred']==0)].shape

(87, 2)

In [103]:
from sklearn.metrics import accuracy_score
acc_score=accuracy_score(y_test.values,predicted_values) *100

In [104]:
error=100-acc_score

In [106]:
error

32.40223463687151

In [ ]:
### Cross Validation : K Fold validation

In [108]:
from sklearn.model_selection import cross_val_score
kn=KNeighborsClassifier()
scores=cross_val_score(kn,x_train,y_train,cv=10)

In [109]:
scores

array([0.59722222, 0.66666667, 0.66197183, 0.67605634, 0.64788732,
       0.61971831, 0.63380282, 0.61971831, 0.5915493 , 0.67605634])

In [110]:
# Grid Search CV

In [111]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=5)
kn.fit(x_train,y_train)
predicted_values=kn.predict(x_test)
print(predicted_values)

[1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 1 1 1
 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0
 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1]


In [114]:
from sklearn.model_selection import GridSearchCV

In [115]:
param_grid={'metric': ['euclidean','manhattan'], 'n_neighbors' : [5,6,7,8,9,4]}

In [116]:
grid_search=GridSearchCV(estimator=kn,param_grid=param_grid)
grid_search.fit(x_train, y_train)
grid_search.best_score_
grid_search.best_estimator_.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'euclidean',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 7,
 'p': 2,
 'weights': 'uniform'}

In [117]:
grid_search.best_score_

0.6685610164483404

In [113]:
### Model Deployment

In [ ]:
#https://dash-gallery.plotly.host/dash-object-detection/

In [ ]:
#Model deployment consumption for common user

In [ ]:
#Exceeutable across the different technologies
# Serialization(pickel file)
# An URL where (post(Testing Data) and Get methods(Response) : API)
# Deploying in cloud so that everyone can use the API
#Flask/Django  

In [ ]:
#AWS, Azure, GoogleCloud, Heruko